services:
  nginx:
    image: nginx:latest
    container_name: reader-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - reader-static:/usr/share/nginx/html/static
      - ./backend/static/images:/usr/share/nginx/html/static/images
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - reader-network
    depends_on:
      - backend

  db:
    image: postgres:18
    container_name: reader-db
    env_file:
      - path: ./backend/db.env
        required: true
    volumes:
      - ./db/data:/var/lib/postgresql
    networks:
      - reader-network

  backend:
    image: reader:latest
    container_name: reader-backend
    env_file:
      - path: ./backend/.env
        required: true
      - path: ./backend/db.env
        required: false
    environment:
      - CONFIG_FILE_PATH=/opt/backend/configurations/local.yaml
    volumes:
      - ./backend/configurations:/opt/backend/configurations
      - ./backend/src:/opt/backend/src
      - reader-static:/opt/backend/static
    networks:
      - reader-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  reader-network:
    external: false

volumes:
  reader-static:
    external: false
